### ISSUE TITLE
How can I add a Marker on map?

### ISSUE THREAD

**Issue by ChristianMEC** [jmarceli/react-hook-google-maps#3]
Thank you for your work on this library.

I didn't figure out how can I add a marker point to the map. Can you give me a hint ... pls?

**Comment by ChristianMEC** [comment]
I found out
```
const GoogleMap = () => {
  const { ref, map, google } = useGoogleMaps(
    process.env.GOOGLE_MAPS_KEY,
    {
      center: { lat, lng },
      zoom: 15,
      scrollwheel: false,
      zoomControl: true,
      mapTypeId: 'satellite'
    }
  );

  if (google !== undefined && google.maps !== undefined ){ 
    const marker = new google.maps.Marker({
      position: { lat, lng },
      map: map,
    });

    marker.setMap(map)
  }

  return (
    <div ref={ref} style={{ width: '100%', height: '100%' }} />
  )
};
```

**Comment by jmarceli** [comment]
Hi, I'm glad you've found that. Sorry for lack of reply but I didn't spot notification about your question. Thanks for sharing the code for others.

**Comment by jmarceli** [comment]
Btw. there is an example in this repo in the `example` dir, see https://github.com/jmarceli/react-hook-google-maps/blob/master/example/src/MapWithMarker.tsx or Codesandbox made from this code https://codesandbox.io/s/react-hook-google-maps-twb4t?file=/src/MapWithMarker.tsx
